# Photo Scanner Script
# Run this whenever you add/remove photos from the featured or gallery folders.
# It regenerates src/data/photos.ts
#   powershell -ExecutionPolicy Bypass -File ".\update-photos.ps1"

$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$websiteRoot = $scriptPath

$featuredPath = Join-Path $websiteRoot "public\images\photos\featured"
$galleryPath = Join-Path $websiteRoot "public\images\photos\gallery"
$outputPath = Join-Path $websiteRoot "src\data\photos.ts"

# Get image files from a folder
function Get-PhotoEntries {
    param (
        [string]$folderPath,
        [string]$relativePath,
        [string]$idPrefix
    )

    $photos = @()
    $extensions = @("*.jpg", "*.jpeg", "*.png", "*.gif", "*.webp")
    $counter = 1

    foreach ($ext in $extensions) {
        $files = Get-ChildItem -Path $folderPath -Filter $ext -ErrorAction SilentlyContinue
        foreach ($file in $files) {
            # Use filename without extension as the title/alt
            $title = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
            $photos += @{
                id = "$idPrefix$counter"
                title = $title
                image = "$relativePath/$($file.Name)" -replace '\\', '/'
                alt = $title
            }
            $counter++
        }
    }

    return $photos
}

Write-Host "Scanning photo folders..." -ForegroundColor Cyan

# Get featured photos (paths are root-absolute so they resolve on any route)
$featuredPhotos = @()
if (Test-Path $featuredPath) {
    $featuredPhotos = Get-PhotoEntries -folderPath $featuredPath -relativePath "/images/photos/featured" -idPrefix "featured"
    Write-Host "Found $($featuredPhotos.Count) featured photos" -ForegroundColor Green
} else {
    Write-Host "Featured folder not found: $featuredPath" -ForegroundColor Yellow
}

# Get gallery photos
$galleryPhotos = @()
if (Test-Path $galleryPath) {
    $galleryPhotos = Get-PhotoEntries -folderPath $galleryPath -relativePath "/images/photos/gallery" -idPrefix "gallery"
    Write-Host "Found $($galleryPhotos.Count) gallery photos" -ForegroundColor Green
} else {
    Write-Host "Gallery folder not found: $galleryPath" -ForegroundColor Yellow
}

function Format-PhotoArray {
    param ([array]$photos)
    $lines = @()
    foreach ($photo in $photos) {
        $lines += "    { id: `"$($photo.id)`", title: `"$($photo.title)`", image: `"$($photo.image)`", alt: `"$($photo.alt)`" },"
    }
    return ($lines -join "`n")
}

# Generate TypeScript content
$tsContent = @"
import type { PhotosData } from "../types/content";

// AUTO-GENERATED by update-photos.ps1 - do not edit manually.
// Last updated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
export const PHOTOS_DATA: PhotosData = {
  featured: [
$(Format-PhotoArray $featuredPhotos)
  ],
  gallery: [
$(Format-PhotoArray $galleryPhotos)
  ],
};
"@

# Write to file
$tsContent | Out-File -FilePath $outputPath -Encoding UTF8
Write-Host "`nGenerated $outputPath" -ForegroundColor Cyan
Write-Host "Total: $($featuredPhotos.Count) featured, $($galleryPhotos.Count) gallery photos" -ForegroundColor Green
