# Photo Scanner Script
# Run this script whenever you add/remove photos from the featured or gallery folders
# It will automatically regenerate data/photos.js

$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$websiteRoot = $scriptPath

$featuredPath = Join-Path $websiteRoot "images\photos\featured"
$galleryPath = Join-Path $websiteRoot "images\photos\gallery"
$outputPath = Join-Path $websiteRoot "data\photos.js"

# Get image files from a folder
function Get-PhotoEntries {
    param (
        [string]$folderPath,
        [string]$relativePath,
        [string]$idPrefix
    )
    
    $photos = @()
    $extensions = @("*.jpg", "*.jpeg", "*.png", "*.gif", "*.webp")
    $counter = 1
    
    foreach ($ext in $extensions) {
        $files = Get-ChildItem -Path $folderPath -Filter $ext -ErrorAction SilentlyContinue
        foreach ($file in $files) {
            # Use filename without extension as the title/alt
            $title = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
            $photos += @{
                id = "$idPrefix$counter"
                title = $title
                image = "$relativePath/$($file.Name)" -replace '\\', '/'
                alt = $title
            }
            $counter++
        }
    }
    
    return $photos
}

Write-Host "Scanning photo folders..." -ForegroundColor Cyan

# Get featured photos
$featuredPhotos = @()
if (Test-Path $featuredPath) {
    $featuredPhotos = Get-PhotoEntries -folderPath $featuredPath -relativePath "images/photos/featured" -idPrefix "featured"
    Write-Host "Found $($featuredPhotos.Count) featured photos" -ForegroundColor Green
} else {
    Write-Host "Featured folder not found: $featuredPath" -ForegroundColor Yellow
}

# Get gallery photos
$galleryPhotos = @()
if (Test-Path $galleryPath) {
    $galleryPhotos = Get-PhotoEntries -folderPath $galleryPath -relativePath "images/photos/gallery" -idPrefix "gallery"
    Write-Host "Found $($galleryPhotos.Count) gallery photos" -ForegroundColor Green
} else {
    Write-Host "Gallery folder not found: $galleryPath" -ForegroundColor Yellow
}

# Generate JS content
$jsContent = @"
// Photos Data - AUTO-GENERATED by powershell -ExecutionPolicy Bypass -File ".\update-photos.ps1"
// Do not edit manually! Run the script to regenerate.
// Last updated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

const PHOTOS_DATA = {
    featured: [
"@

# Add featured photos
for ($i = 0; $i -lt $featuredPhotos.Count; $i++) {
    $photo = $featuredPhotos[$i]
    $comma = if ($i -lt $featuredPhotos.Count - 1) { "," } else { "" }
    $jsContent += @"

        {
            id: "$($photo.id)",
            title: "$($photo.title)",
            image: "$($photo.image)",
            alt: "$($photo.alt)"
        }$comma
"@
}

$jsContent += @"

    ],
    gallery: [
"@

# Add gallery photos
for ($i = 0; $i -lt $galleryPhotos.Count; $i++) {
    $photo = $galleryPhotos[$i]
    $comma = if ($i -lt $galleryPhotos.Count - 1) { "," } else { "" }
    $jsContent += @"

        {
            id: "$($photo.id)",
            title: "$($photo.title)",
            image: "$($photo.image)",
            alt: "$($photo.alt)"
        }$comma
"@
}

$jsContent += @"

    ]
};
"@

# Write to file
$jsContent | Out-File -FilePath $outputPath -Encoding UTF8
Write-Host "`nGenerated $outputPath" -ForegroundColor Cyan
Write-Host "Total: $($featuredPhotos.Count) featured, $($galleryPhotos.Count) gallery photos" -ForegroundColor Green
